[package]
name = "mission_editor_rust_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cc = "1"

[dependencies]
ash = { version = "0.38", default-features = false, features = ["loaded", "std"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "unwind"

[profile.dev]
panic = "unwind"
